In [2]:
from IPython.display import display
from datetime import datetime
import pandas as pd
import time
    
def wordclock_func():

    
    #prints as YYYY-MM-DD HH:MM:SS.MS
    now = datetime.now()

    light_array = [[1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   ]

    current_time_mil = int('1725')
    current_day_week = now.today().weekday()

    if current_time_mil >= 1200:
        am_pm = 'PM'
        current_time_EST = current_time_mil - 1200
    else:
        am_pm = 'AM'
        current_time_EST = current_time_mil

    minutes = int(str(current_time_EST)[-2:])
    try:
        hour = int(str(current_time_EST)[:-2])
    except ValueError:
        hour = 0
        
    #PAST
    #HALF (30), TWENTYFIVE (25), TWENTY (20), QUARTER (15), TEN (10), FIVE (5)

    #OCLOCK
    if minutes < 5:
        light_array[9] = [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
    #PAST
    if 5 <= minutes < 10: #FIVE PAST
        light_array[3] = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
        light_array[4] = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    elif 10 <= minutes < 15: #TEN PAST
        light_array[1] = [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
        light_array[4] = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    elif 15 <= minutes < 20: #QUARTER PAST
        light_array[2] = [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
        light_array[4] = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    elif 20 <= minutes < 25: #TWENTY PAST
        light_array[3] = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
        light_array[4] = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    elif 25 <= minutes < 30: #TWENTYFIVE PAST
        light_array[3] = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
        light_array[4] = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    elif 30 <= minutes < 35: #HALF PAST
        light_array[1] = [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
        light_array[4] = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    #TO
    elif 35 <= minutes < 40: #TWENTYFIVE TO
        hour += 1
        light_array[3] = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
        light_array[4] = [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    elif 40 <= minutes < 45: #TWENTY TO
        hour += 1
        light_array[3] = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
        light_array[4] = [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    elif 45 <= minutes < 50: #QUARTER TO
        hour += 1
        light_array[2] = [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
        light_array[4] = [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    elif 50 <= minutes < 55: #TEN TO
        hour += 1
        light_array[1] = [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0]
        light_array[4] = [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    elif minutes >= 55: #FIVE TO
        hour += 1
        light_array[3] = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
        light_array[4] = [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    #HOUR LIGHT ARRAY
    if hour == 1:
        light_array[4][8] = 1
        light_array[4][9] = 1
        light_array[4][10] = 1
    elif hour == 2:
        light_array[8] = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    elif hour == 3:
        light_array[6] = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
    elif hour == 4:
        light_array[5] = [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    elif hour == 5:
        light_array[5] = [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0]
    elif hour == 6:
        light_array[5] = [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0]
    elif hour == 7:
        light_array[7] = [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
    elif hour == 8:
        light_array[7] = [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0]
    elif hour == 9:
        light_array[9] = [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    elif hour == 10:
        light_array[8] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]
    elif hour == 11:
        light_array[6] = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    elif hour == 12:
        light_array[8] = [0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0]

    #DAY LIGHT ARRAY
    if current_day_week+1 == 1:
        light_array[11] = [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    if current_day_week+1 == 2:
        light_array[11] = [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    if current_day_week+1 == 3:
        light_array[11] = [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    if current_day_week+1 == 4:
        light_array[11] = [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]
    if current_day_week+1 == 5:
        light_array[11] = [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
    if current_day_week+1 == 6:
        light_array[11] = [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0]
    if current_day_week+1 == 7:
        light_array[11] = [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0]

    #AM/PM LIGHT ARRAY
    if am_pm == 'AM':
        light_array[11][8] = 3
        light_array[11][9] = 3
    if am_pm == 'PM':
        light_array[11][10] = 3
        light_array[11][11] = 3

    #LISTS
    col1 = [
            ['I', 'T', 'N', 'I', 'S', 'O', 'F', 'M', 'T', 'E', 'M', 'P'],
            ['W', 'R', 'H', 'A', 'L', 'F', 'T', 'E', 'N', 'V', 'K', 'C'],
            ['I', 'N', 'Q', 'U', 'A', 'R', 'T', 'E', 'R', 'U', 'T', 'P'],
            ['F', 'T', 'W', 'E', 'N', 'T', 'Y', 'F', 'I', 'V', 'E', 'T'],
            ['A', 'T', 'O', 'P', 'A', 'S', 'T', 'X', 'O', 'N', 'E', 'K'],
            ['F', 'O', 'U', 'R', 'F', 'I', 'V', 'E', 'S', 'I', 'X', 'J'],
            ['B', 'E', 'L', 'E', 'V', 'E', 'N', 'T', 'H', 'R', 'E', 'E'],
            ['N', 'S', 'E', 'V', 'E', 'N', 'E', 'I', 'G', 'H', 'T', 'K'],
            ['T', 'W', 'O', 'T', 'W', 'E', 'L', 'V', 'E', 'T', 'E', 'N'],
            ['N', 'I', 'N', 'E', 'P', 'J', 'O', 'C', 'L', 'O', 'C', 'K'],
            ['H', 'W', 'Y', 'A', 'E', 'O', 'U', 'T', 'S', 'I', 'D', 'E'],
            ['M', 'T', 'W', 'T', 'F', 'S', 'S', 'Q', 'A', 'M', 'P', 'M']
            ]


    df1 = pd.DataFrame(col1)
    df2 = pd.DataFrame(light_array)

    #USE LIGHT_ARRAY 

    def light_up(s):
        if s == 0:
            light = 'color: #353535'
        elif s == 1:
            light = 'color: white'
        elif s == 2:
            light = 'color: red'
        elif s == 3:
            light = 'color: blue'
        return light

    styled_df1 = df1.style.apply(lambda x: df2.applymap(light_up), axis=None).set_properties(**{'border-color': '#202020', 'background-color': '#202020','width':'75px','height':'75px','font-size':'25pt','text-align': 'center'})
    
    display(styled_df1)

wordclock_func()